services:
  # MongoDB
  mongodb:
    container_name: database_container_prod
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  # Express API
  server:
    build: ./server
    container_name: express_api
    ports:
      - 4000:3000
    environment:
      APP_NAME: LearnDocker
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/dockerlearn
    depends_on:
      - mongodb

  # React Frontend
  client:
    build: ./client
    container_name: react_app
    ports:
      - 8080:80
    depends_on:
      - server

volumes:
  mongodb: {}