version: "3"

services:
  #MongoDB
  mongodb:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      APP_NAME: LearnDocker
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/dockerlearn
    depends_on:
      - mongodb

volumes:
  mongodb: {}